name: Build-and-deploy-win
run-name: ${{ github.actor }} is building a Windows release for SODA

on:
  push:
    branches:
      - main
      - staging
      - pre-staging

jobs:
  deploy-on-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: env-electron-python
          environment-file: tools/anaconda-env/environment-Windows.yml
          auto-update-conda: true
          auto-activate-base: false
      - run: |
          conda activate  env-electron-python
          conda info
          conda list

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Install package.json modules and their dependencies
        run: npm install --ignore-scripts

      - name: Build the app

        run: |
          npm run build:win

      - name: Upload Release Asset - exe thing again
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/soda-for-sparc-15.4.1-beta.exe
          asset_name: SODA-for-SPARC-15.4.1-beta.exe
          asset_content_type: application/octet-stream
